-- Steel City H3 — Phase 1 schema
--
-- Run this in the Supabase SQL Editor on the steelcityh3 project
-- (Dashboard → SQL Editor → New query → paste → Run).
--
-- What this sets up:
--   * Three tables: profiles, events, user_roles
--   * Two enums: event_status, user_role
--   * is_admin() helper for RLS policies
--   * Trigger to auto-create a profiles row when someone signs up
--   * Trigger to keep updated_at fresh on every row UPDATE
--   * Row-Level Security policies matching the Phase 1 brief
--
-- Safe to re-run during development (drops & recreates policies/triggers).

-- ============================================================================
-- 1. Enums
-- ============================================================================

do $$ begin
  create type public.event_status as enum ('open', 'hares_wanted', 'closed', 'completed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.user_role as enum ('admin');
exception when duplicate_object then null; end $$;


-- ============================================================================
-- 2. Tables
-- ============================================================================

-- profiles: 1:1 with auth.users. Trigger (below) auto-creates a row on signup
-- with NULLs for the fields the user fills in on /complete-profile.
-- "Profile complete" is checked via `real_name is not null and phone is not null`.
create table if not exists public.profiles (
  id                  uuid primary key references auth.users(id) on delete cascade,
  real_name           text,
  hash_name           text,
  phone               text,
  is_hash_virgin      boolean     not null default true,
  newsletter_opt_in   boolean     not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- events: PK is plain integer (not bigint) to match the existing ?id=18 URLs.
-- "generated by default as identity" lets the seed migration insert explicit ids,
-- and lets admins create new events without specifying one.
create table if not exists public.events (
  id                  integer primary key generated by default as identity,
  run_number          integer            not null,
  title               text               not null,
  event_date          date               not null,
  start_time          time               not null default '12:00',
  location_summary    text               not null,
  location_full       text,
  hares               text,
  pace                text               not null default 'Walk or run',
  status              public.event_status not null default 'open',
  description         text,
  distance_miles      numeric(4,1),
  on_on_pub           text,
  scribe_report       text,
  scribe_report_by    text,
  charity_raised      numeric(10,2),
  amount_per_head     numeric(10,2)      not null default 5.00,
  created_at          timestamptz        not null default now(),
  updated_at          timestamptz        not null default now()
);

-- user_roles: composite PK lets a single user accumulate multiple roles
-- in later phases (editor, scribe, hare) without schema changes.
create table if not exists public.user_roles (
  user_id     uuid             not null references public.profiles(id) on delete cascade,
  role        public.user_role not null,
  granted_by  uuid             references public.profiles(id),
  granted_at  timestamptz      not null default now(),
  primary key (user_id, role)
);


-- ============================================================================
-- 3. updated_at trigger
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at on public.profiles;
create trigger set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.events;
create trigger set_updated_at
  before update on public.events
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 4. auth.users → profiles trigger
-- ============================================================================
-- Fires after Supabase creates the auth.users row (i.e. after the user clicks
-- their magic link for the first time). Creates a blank profiles row that the
-- /complete-profile form will then fill in.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ============================================================================
-- 5. is_admin() helper
-- ============================================================================
-- SECURITY DEFINER so it bypasses the user_roles RLS (which is admin-only read).
-- Without that, a non-admin's query couldn't even check if they were an admin.

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = uid and role = 'admin'
  );
$$;


-- ============================================================================
-- 6. Row-Level Security — profiles
-- ============================================================================
-- Read your own row, or all rows if you're admin.
-- Update your own row, or any row if you're admin.
-- Delete only by admin. No client-side insert (handled by trigger).

alter table public.profiles enable row level security;

drop policy if exists "profiles: read own"           on public.profiles;
drop policy if exists "profiles: read all (admin)"   on public.profiles;
drop policy if exists "profiles: update own"         on public.profiles;
drop policy if exists "profiles: update any (admin)" on public.profiles;
drop policy if exists "profiles: delete (admin)"     on public.profiles;

create policy "profiles: read own"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles: read all (admin)"
  on public.profiles for select
  using (public.is_admin(auth.uid()));

create policy "profiles: update own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "profiles: update any (admin)"
  on public.profiles for update
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

create policy "profiles: delete (admin)"
  on public.profiles for delete
  using (public.is_admin(auth.uid()));


-- ============================================================================
-- 7. Row-Level Security — events
-- ============================================================================
-- Public read (incl. anonymous visitors). Admin-only write.

alter table public.events enable row level security;

drop policy if exists "events: public read"  on public.events;
drop policy if exists "events: admin insert" on public.events;
drop policy if exists "events: admin update" on public.events;
drop policy if exists "events: admin delete" on public.events;

create policy "events: public read"
  on public.events for select
  using (true);

create policy "events: admin insert"
  on public.events for insert
  with check (public.is_admin(auth.uid()));

create policy "events: admin update"
  on public.events for update
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

create policy "events: admin delete"
  on public.events for delete
  using (public.is_admin(auth.uid()));


-- ============================================================================
-- 8. Row-Level Security — user_roles
-- ============================================================================
-- Admin-only for everything. is_admin() is SECURITY DEFINER so it can still
-- check membership from inside a non-admin's session.

alter table public.user_roles enable row level security;

drop policy if exists "user_roles: admin read"   on public.user_roles;
drop policy if exists "user_roles: admin insert" on public.user_roles;
drop policy if exists "user_roles: admin update" on public.user_roles;
drop policy if exists "user_roles: admin delete" on public.user_roles;

create policy "user_roles: admin read"
  on public.user_roles for select
  using (public.is_admin(auth.uid()));

create policy "user_roles: admin insert"
  on public.user_roles for insert
  with check (public.is_admin(auth.uid()));

create policy "user_roles: admin update"
  on public.user_roles for update
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

create policy "user_roles: admin delete"
  on public.user_roles for delete
  using (public.is_admin(auth.uid()));


-- ============================================================================
-- 9. Grants
-- ============================================================================
-- The PostgREST roles (anon, authenticated) need table-level privileges before
-- RLS policies can even be evaluated. Without these GRANTs, the API returns
-- "permission denied" before reaching RLS.

grant select                         on public.events     to anon, authenticated;
grant select, update                 on public.profiles   to authenticated;
grant select, insert, update, delete on public.user_roles to authenticated;


-- ============================================================================
-- Done. Next: run 0002_phase1_seed_events.sql to load events #13–21.
-- ============================================================================
